# Put parameters here that don't need to change on each machine where the app is deployed
parameters:
  postgres.url: 'postgresql://%env(POSTGRES_USER)%:%env(POSTGRES_PASSWORD)%@%env(POSTGRES_HOST)%:%env(POSTGRES_PORT)%/%env(POSTGRES_DATABASE)%?serverVersion=%env(POSTGRES_SERVER_VERSION)%&charset=utf8'

  # JWT
  jwt.access_token_ttl: 3600
  jwt.refresh_token_ttl: 2592000
  jwt.refresh_token_rotate: true
  jwt.secret_key: '%env(resolve:JWT_SECRET_KEY)%'
  jwt.public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
  jwt.pass_phrase: '%env(JWT_PASSPHRASE)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\:
    resource: '../src/*'
    exclude: '../src/{Entity,Migrations,Tests}'


  App\Controller\:
    resource: '../src/Controller/*'
    tags: [ 'controller.service_arguments' ]

  App\Resolver\RequestValidator:
    tags:
      - { name: controller.argument_value_resolver, priority: 50 }

  App\Plugin\:
    resource: '../src/Plugin/*'
    exclude: '../src/Plugin/{PluginManager.php}'
    tags: [ 'app.chat_plugin' ]

  App\Plugin\PluginManager:
    arguments:
      $plugins: !tagged_iterator 'app.chat_plugin'
    tags:
      - { name: kernel.event_subscriber }

  App\Exception\GlobalExceptionSubscriber:
    tags:
      - { name: kernel.event_subscriber }
