nelmio_cors:
  defaults:
    allow_origin: ['http://localhost:4200', 'http://localhost:63342','http://localhost:8080']
    allow_headers: ['Content-Type', 'Authorization']
    allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
    expose_headers: ['Authorization']
    max_age: 3600
  paths:
    '^/': ~
