security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    # Login endpoint: issues JWT on success via Lexik handlers
    login:
      pattern: ^/auth/login$
      stateless: true
      provider: app_user_provider
      json_login:
        check_path: /auth/login
        username_path: email
        password_path: password
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    # Protect everything under /api with JWT
    api:
      pattern: ^/api
      stateless: true
      provider: app_user_provider
      jwt: ~   # provided by Lexik

    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

  access_control:
    - { path: ^/auth/login$, roles: PUBLIC_ACCESS }
    - { path: ^/api/v1/health$, roles: PUBLIC_ACCESS }
    - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
