security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: username

  firewalls:
    # Symfony profiler, assets, etc.
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    # Public authentication endpoints (login/register/refresh)
    auth:
      pattern: ^/api/v1/auth/
      stateless: true
      provider: app_user_provider
      security: false   # Explicitly allow anonymous access for auth routes

    # Main API firewall using JWT authentication
    api:
      pattern: ^/api/
      stateless: true
      provider: app_user_provider
      jwt: ~            # Provided by LexikJWTAuthenticationBundle

  access_control:
    - { path: ^/api/v1/health$, roles: PUBLIC_ACCESS }

    - { path: ^/api/v1/auth, roles: PUBLIC_ACCESS }

    - { path: ^/api/v1/message, roles: ROLE_USER }
    - { path: ^/api/v1/messages, roles: ROLE_USER }

    - { path: ^/api/, roles: IS_AUTHENTICATED_FULLY }
